name: Build

on:
    push:
        branches: ["main"]
    pull_request:
        branches: ["main"]

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout repository
              uses: actions/checkout@v3
              with:
                  fetch-depth: 0

            - name: Install dependencies
              run: sudo apt -y install build-essential libprocps-dev

            - name: Build fetcho
              run: make RELEASE=1 clean build

            - name: Build .deb file
              run: |
                  version=$(git describe --tags --abbrev=0)
                  version="${version:1}"

                  mkdir -p stage/DEBIAN
                  mkdir -p stage/usr/bin
                  cp control stage/DEBIAN/control

                  sed 's|@DEB_ARCH@|amd64|g' -i stage/DEBIAN/control
                  sed 's|@DEB_VERSION@|$version|g' -i stage/DEBIAN/control

                  install -Dm644 build/release/bin/fetcho stage/usr/bin/fetcho
                  chmod +x stage/usr/bin/fetcho

                  dpkg-deb -b stage fetcho.deb
                  mv fetcho.deb build/release/bin/fetcho.deb
                  rm -rf stage

            - name: Upload binary
              uses: actions/upload-artifact@v3
              with:
                  name: fetcho
                  path: build/release/bin/fetcho

            - name: Upload .deb
              uses: actions/upload-artifact@v3
              with:
                  name: fetcho.deb
                  path: build/release/bin/fetcho.deb
